// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "3ce1e22a-00eb-4b45-8573-1bd42b3ac64c");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 3);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1678960805);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1678960784);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1678960781);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1678960925);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1678960837);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.E7CF176E110C211B", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{84444806-9c0d-4a4c-a4c7-93f3ddec50d0}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e4d939b6-0a90-4c11-b5c7-48867a53d58d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1678960782);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1678960838594");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1678962650594");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1678960816321");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1678982416321");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220829141339");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220829141339");
user_pref("browser.startup.homepage_override.mstone", "104.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1678960793);
user_pref("browser.theme.content-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.iniFile.exists.appversion", "104.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ID");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "8bcfaa32916944abab1d49772ee9bacc");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220829141339");
user_pref("extensions.lastAppVersion", "104.0.1");
user_pref("extensions.lastPlatformVersion", "104.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a2ce8edc-94e8-4a3c-a92d-12e5eaa2ecdb\",\"formautofill@mozilla.org\":\"bbde91ab-d9e3-46c2-9ad4-88c154881e2f\",\"pictureinpicture@mozilla.org\":\"50bb7fc2-21df-4a03-bb60-f761f9be6773\",\"screenshots@mozilla.org\":\"5c901b64-2c61-4d9d-953d-12d99eff5fee\",\"webcompat-reporter@mozilla.org\":\"e074d4c5-97e9-4347-9ae7-28d62d978314\",\"webcompat@mozilla.org\":\"addfa8c6-1ac9-4889-8410-6acbf5f27ab0\",\"default-theme@mozilla.org\":\"1172e131-80eb-41a0-940b-ee3224b2953a\",\"addons-search-detection@mozilla.com\":\"48caecd3-d4d1-4d10-8823-cbb5fa2f36ba\",\"google@search.mozilla.org\":\"8866a3b5-90bb-4af5-9938-027e9e9e9752\",\"amazondotcom@search.mozilla.org\":\"890606c2-2dd5-4bdd-8912-b0e67cf51870\",\"wikipedia@search.mozilla.org\":\"4927cefa-93c1-4097-8eca-43b6d691d606\",\"bing@search.mozilla.org\":\"687526be-104a-45a5-ba98-7a7261991f6f\",\"ddg@search.mozilla.org\":\"17fb4630-3dfc-4671-af76-f90df76945de\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1678960839);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20220829141339");
user_pref("gfx-shader-check.device-id", "0x22b1");
user_pref("gfx-shader-check.driver-version", "20.19.15.4360");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1678960951);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1678960951);
user_pref("media.gmp-manager.buildID", "20220829141339");
user_pref("media.gmp-manager.lastCheck", 1678960951);
user_pref("media.gmp-widevinecdm.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, reason: error");
user_pref("media.gmp-widevinecdm.lastDownloadFailed", 1678960951);
user_pref("media.gmp-widevinecdm.lastInstallStart", 1678960951);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x22b1");
user_pref("sanity-test.driver-version", "20.19.15.4360");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20220829141339");
user_pref("security.sandbox.content.tempDirSuffix", "{ebffb75f-8716-47b0-a518-48afed744d32}");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1678960713);
user_pref("toolkit.telemetry.cachedClientID", "e971926e-56fc-440b-8674-199cebef44b6");
user_pref("toolkit.telemetry.previousBuildID", "20220829141339");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
